version: 2

seeds:
  - name: order_status
    description: "Dictionary for SalesOrderHeader.Status."
    columns:
      - name: order_status_code
        description: "Status code from the OLTP (SalesOrderHeader.Status)."
        tests:
          - not_null
          - unique
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6]

      - name: order_status_name
        description: "Human-readable status name."
        tests:
          - not_null
          - accepted_values:
              values:
                - In process
                - Approved
                - Backordered
                - Rejected
                - Shipped
                - Cancelled
